# POST http://localhost:4242/create-payment
# Content-Type: application/json

# { 
#   "paymentMethod": "card",
#   "amount": 50, 
#   "currency": "usd" 
# }


POST http://localhost:4242/create-card-payment
Content-Type: application/json

{ 
  "amount": 50, 
  "currency": "usd" 
}